#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import rospy
from gps_trans.gps_transform_node import gps_transform_node

try:
    gps_tf = gps_transform_node()
    gps_tf._execute()
except rospy.ROSInterruptException:
    pass
