#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from nitrabot_remote.nitrabot_remote_node import NitrabotRemoteNode

try:
    nitrabot_remote_node = NitrabotRemoteNode()
    nitrabot_remote_node.run()
except rospy.ROSInterruptException:
    pass
