industrial_robot:
  # Velocity Controllers ---------------------------------------
  left_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_support_left_to_wheel_left
    pid: {p: 120.0, i: 0.01, d: 10.0}
  right_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_support_right_to_wheel_right
    pid: {p: 120.0, i: 0.01, d: 10.0}
