#Common parameters
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true 
  transform_time_offset: 0.0
  transform_timeout: 0.0

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  print_diagnostics: true
  debug: false
  publish_tf: true
  use_control: false

#Wheel Odometry
  odom0: /wheel/odom   
  odom0_config: [false,  false,  false,   # x,   y,   z
                 false,  false,  false,   # r,   p,   w (yaw)
                 true,   true,   false,   # dx,  dy,  dz
                 false,  false,  true,    # dr,  dp,  dw
                 false,  false,  false,]  # ddx, ddy, ddz
  odom0_queue_size: 10
  odom0_differential: true
  odom0_relative: false
  odom0_nodelay: true

#IMU
  imu0: imu/data
  imu0_config: [false,  false, false,    # x,   y,   z
                false,  false,  true,    # r,   p,   w (yaw)
                false,  false, false,    # dx,  dy,  dz
                false,  false,  true,    # dr,  dp,  dw
                true,   false,  false,]   # ddx, ddy, ddz
  imu0_queue_size: 10
  imu0_differential: false
  imu0_relative: false
  imu0_nodelay: true

  imu0_remove_gravitational_acceleration: true
  gravitational_acceleration: 9.80665

#Covariance
  process_noise_covariance: [0.05,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0, 0.05,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0, 0.06,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0, 0.03,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0, 0.03,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0, 0.06,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,0.025,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0, 0.025,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,  0.04,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0, 0.01,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0, 0.01,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0, 0.02,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0, 0.01,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0, 0.01,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0, 0.015]
  
  initial_estimate_covariance:  [1e-9,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,     0,     0,     0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,     0,     0,     0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,     0,     0,     0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0, 1e-9,     0,     0,     0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  1e-9,     0,     0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,  1e-9,     0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,  1e-9,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0, 1e-9,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0, 1e-9]
