version: '3'

services:
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    network_mode: host
    
  nitra_robot:
    user: root
    depends_on: 
      - ros-master
    image: nitra_robot:latest
    build:
      context: ..
      dockerfile: ./nitrabot_dockerfiles/Dockerfile
    container_name: nitrabot-ros 
    volumes:
      - "../:/root/catkin_ws/src/"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/tmp/.docker.xauth:/tmp/.docker.xauth"
    environment:
      - "DISPLAY=$DISPLAY"
      - "XAUTHORITY=/tmp/.docker.xauth"
      - "QT_X11_NO_MITSHM=1"
    privileged: True
    network_mode: host
    entrypoint:
      - tail 
      - -f
      - /dev/null
