version: '3'

services:
  ros-master:
    image: ros:melodic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    network_mode: host
    
  nitra_robot:
    user: root
    depends_on: 
      - ros-master
    image: nitra_robot:latest
    build:
      context: ..
      dockerfile: ./nitrabot_dockerfiles/Dockerfile
    container_name: nitrabot-ros 
    volumes:
      - "../:/root/catkin_ws/src/"
    devices:
     - /dev/ttyACM0:/dev/ttyACM0
     - /dev/ttyACM1:/dev/ttyACM1
     - /dev/ttyACM1:/dev/ttyACM2
     - /dev/ttyACM0:/dev/ttyUSB0
      # - /dev/ttyACM0:/dev/ttyUSB1
    privileged: True
    network_mode: host
    entrypoint:
      - tail 
      - -f
      - /dev/null
