#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import rospy
from bumper_control.bumper_control import BumperControl

try:
    bumper_control_node = BumperControl()
    bumper_control_node.run()
except rospy.ROSInterruptException:
    pass
